// <auto-generated />
namespace TelNet.Migrations.TelNetContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dobavljaciRatings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dobavljaciRatings));
        
        string IMigrationMetadata.Id
        {
            get { return "201705241100383_dobavljaciRatings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
