// <auto-generated />
namespace TelNet.Migrations.TelNetContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NarudzbaKupac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NarudzbaKupac));
        
        string IMigrationMetadata.Id
        {
            get { return "201706021755267_NarudzbaKupac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
