// <auto-generated />
namespace TelNet.Migrations.TelNetContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NarudzbaPaket4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NarudzbaPaket4));
        
        string IMigrationMetadata.Id
        {
            get { return "201706022009564_NarudzbaPaket4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
